#! /bin/sh
# Utility to create manufacturer's OUI table

#
# 2005/04/05 : jean : adaptation pour unicode
#

args=
refresh=0

while [ $# -gt 0 ]
do
    case "$1" in
    --refresh|--fetch|-r)
        refresh=1
        ;;
    --norefresh|--nofetch)
        refresh=0
        ;;
    --help)
        echo "Usage: $0 --[no]refresh dbname"
        exit
        ;;
    *)
        args="$args $1"
        ;;
    esac
    shift
done

if [ $refresh -gt 0 ]; then

    [ -e oui.latin1 ] && rm -rf oui.latin1
    wget -O oui.latin1 \
	-nd 'http://standards.ieee.org/regauth/oui/oui.txt'

    iconv -f iso8859-1 -t utf-8 < oui.latin1 > oui.txt
    rm -f oui.latin1
fi

awk -f ouiparse.awk < oui.txt | psql -e $args

exit
