#!/bin/sh

export PGDATABASE=mac
export PGUSER=jean
export PGPASSWORD=mot-de-passe-de-mac

/usr/local/bin/psql -q <<EOF

drop table last_ip_mac;
drop table last_by_ip;
drop table ipmac2;

--
-- Extrait pour chaque association ipmac la session la plus recente
--
create table last_ip_mac as
	select idipmac, max(fin) as most_recent_date
	from sessionipmac
	group by idipmac ;
--
-- Extrait les adresses ip des sessions les plus recentes
--
create table last_by_ip as
	select ipmac.ip, ipmac.mac, last_ip_mac.most_recent_date
	from ipmac, last_ip_mac
	where ipmac.idipmac=last_ip_mac.idipmac and family(ipmac.ip)=4;
--
-- Ne conserve que la session la plus recente pour une adresse IP donnee
--
create table ipmac2 as
	select ip, max(most_recent_date) as most_recent_date
	from last_by_ip
	group by ip ;
EOF
