#!/bin/sh

PGDATABASE=mac 
PGHOST=crc.u-strasbg.fr 
PGUSER=jean 
PGPASSWORD="mot-de-passe-de-mac"
export PGDATABASE PGHOST PGUSER PGPASSWORD

PSQL=/usr/local/bin/psql

$PSQL -qc "
DELETE FROM sessionipmac WHERE close=1 AND age(fin) > interval '5 days'
"
$PSQL -qc "
DELETE FROM sessionportmac WHERE close=1 AND age(fin) > interval '5 days'
"
