#!/bin/sh -x

# Script de nettoyage des session ipmac et portmac 
# de la base mac

delais="1 month"
delim=","

PGUSER="jean"
PGPASSWORD="mot-de-passe-de-mac"
export PGUSER PGPASSWORD

SRCHOST="crc"
SRCDB="mac"
DSTHOST="geb"
DSTDB="histomac"

# extraction des associations ipmac, portmac et les equipements
# et insertion dans la base d'historique
for table in ipmac portmac eq
do
    psql -h $DSTHOST -d $DSTDB -Aqtc "DELETE FROM $table"
    psql -h $SRCHOST -d $SRCDB -Aqtc \
	"COPY $table TO STDOUT" | psql -h $DSTHOST -d $DSTDB -Aqtc \
	"COPY $table FROM STDIN"
done

# extraction des sessions closes les plus anciennes
# et insertion dans la base d'historique
for table in sessionipmac sessionportmac ;
do
    psql -h $SRCHOST -d $SRCDB -F"$delim" -Aqtc \
	"SELECT * FROM $table WHERE close=1 AND AGE(fin)>'$delais'" | \
	    psql -h $DSTHOST -d $DSTDB -Aqtc \
		"COPY $table FROM STDIN WITH DELIMITER '$delim'"
done

# suppression des sessions les plus anciennes
for table in sessionipmac sessionportmac ;
do
    psql -h $SRCHOST -d $SRCDB -F"$delim" -Aqtc \
	"DELETE FROM $table WHERE close=1 AND AGE(fin)>'$delais'" 
done
