#!/bin/sh

#
# Wrapper pour ps2pdf
#
# Cette *#~@\¹#!$ de script utilise plein de programmes eux-mêmes
# dans /usr/local/bin.
#
# Pour éviter de compiler le Makefile ou les scripts CGI, ce wrapper
# permet de positionner un PATH cohérent valable pour tous les scripts
# appelés par ps2pdf
#

PATH=/usr/local/bin:$PATH
export PATH

exec ps2pdf $*
