# Created by: Pierre David <pdagog@gmail.com>, Jean Benoit <jean@unistra.fr>
# $FreeBSD: head/net-mgmt/netmagis-www/Makefile 361601 2014-07-12 06:57:47Z pi $

PORTNAME=	netmagis
PKGNAMESUFFIX=	-www

COMMENT=	Netmagis web module

MASTERDIR=	${.CURDIR}/../netmagis-common

PKGMESSAGE=	${.CURDIR}/pkg-message
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
