# Created by: Pierre David <pdagog@gmail.com>, Jean Benoit <jean@unistra.fr>
# $FreeBSD: ports/net-mgmt/netmagis-detecteq/Makefile,v 1.1 2012/10/30 20:32:33 crees Exp $

PORTNAME=	netmagis
PKGNAMESUFFIX=	-detecteq

COMMENT=	Files for detection of equipment modifications

MASTERDIR=	${.CURDIR}/../netmagis-common

PKGMESSAGE=	${.CURDIR}/pkg-message
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
