# Created by: Pierre David <pdagog@gmail.com>, Jean Benoit <jean@unistra.fr>
# $FreeBSD: head/net-mgmt/netmagis-detecteq/Makefile 347842 2014-03-11 05:17:43Z miwi $

PORTNAME=	netmagis
PKGNAMESUFFIX=	-detecteq

COMMENT=	Files for detection of equipment modifications

MASTERDIR=	${.CURDIR}/../netmagis-common

PKGMESSAGE=	${.CURDIR}/pkg-message
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
