#!/bin/sh

#
#
# Création d'une arborescence pour distribuer WebDNS
#
# Usage :
#	mkdist
#
# Historique
#   2004/03/07 : pda      : conception
#   2004/04/16 : pda      : derniers ajustement avant sortie 1.2
#   2005/04/12 : pda      : derniers ajustement avant sortie 1.3
#   2007/11/27 : pda/jean : généralisation et utilisation des arbres CVS
#   2010/10/31 : pda      : simplification
#

TMPDIR=${TMPDIR:-/tmp}

###############################################################################
# Ça sert toujours...

erreur ()
{
    echo "$1. Stop !" >&2
    exit 1
}

###############################################################################
# Extraction de la version courante à partir du Makefile de www
# $1 : fichier Makefile

extraire_version ()
{
    sed -n -e "/^VERSION[ 	]*=/ {
					s/#.*//
					s/VERSION[ 	]*=[ 	]*//
					s/[ 	]*$//
					p
				    }" $1
}

###############################################################################
# Programme principal

if [ $# != 0 ]
then
    erreur "usage: mkdist"
fi

#
# Extraire le numéro de version
#

VERSION="`extraire_version www/Makefile`"
PREFIXE="webdns-$VERSION"

#
# Placer tout cela dans le répertoire destination
#

DESTDIR="$TMPDIR/$PREFIXE"

mkdir $DESTDIR || exit 1

#
# Extraction des fichiers de l'arborescence webdns
#

( cd doc ; make dist) > /dev/null


tar cf - doc expl inst upgrade www pgauth pkgtcl htg CHANGES README \
    | tar xf - -C $DESTDIR

# Pour l'instant, github nous contraint a utiliser UTF8 pour le README.
# en attendant que tout webdns passe en UTF8, on remet le README en
# Latin9.
iconv -f utf-8 -t iso8859-15 < README > $DESTDIR/README

#
# Création des répertoires vides
#

mkdir $DESTDIR/dump

#
# Création du tgz final
#

tar czf $PREFIXE.tgz -C $TMPDIR $PREFIXE

#
# Suppression du répertoire temporaire utilisé pour construire la distribution
#

rm -rf $DESTDIR
