#!/bin/sh

set -e # Stop on first error

# Variables
export DEBEMAIL=jean@unistra.fr
export DEBFULLNAME="Jean BENOIT"

TCLCONF=/usr/lib/tcl8.5/tclConfig.sh

BASEURL=http://www.netmagis.org/files/
if [ $# != 1 ]
then
    echo Usage: $0 version >&2
    exit 1
fi
VERSION=$1

TGZ=netmagis-$VERSION.tar.gz
URL=$BASEURL/$TGZ
QUILTRC=$PWD/quiltrc
dquilt() {
  quilt --quiltrc="$QUILTRC" "$@"
}

PORTSDIR=$PWD/../freebsd

SUBST="-e s/%VERSION%/$VERSION/g"

# Functions

modmakefile()
{
    sed --in-place=.bak \
    	-e "/^TCLCONF/d" \
	-e "/^PREFIX.*/s||PREFIX=|" \
	-e "/^BINDIR/s|/bin|/usr&|" \
	-e "/^SBINDIR/s|/sbin|/usr&|" \
	-e "/^MANDIR/s|/man|/usr&|" \
	-e "/^RCDIR/s|/rc.d|/init.d|" \
	-e "/^CAFILE/s|/.*|/etc/ssl/certs/ca-certificates.crt|" \
	-e "/^NMDOCDIR/s|/share|/usr&|" \
	-e "/^NMXMPDIR/s|/share/.*|/usr/share/doc/netmagis/examples|" \
	-e "/^NMLIBDIR/s|/lib|/usr&|" \
	-e "/^NMCGIDIR/s|/www/netmagis|/usr/lib/cgi-bin/netmagis|" \
	-e "/^NMWSDIR/s|/www/metro|/usr/lib/cgi-bin/metro|" \
	-e "/^PREFIX/a \
TCLCONF=$TCLCONF
" \
    	-e "/^usage:/i \
firsttarget:build\\

" \
	$1
}

geninstall()
{
    src=$1
    dst=$2

    sed \
	-e "/@/d" \
	-e "s|^bin|usr/&|" \
	-e "s|^sbin|usr/&|" \
	-e "s|^lib|usr/&|" \
	-e "s|^www/metro|usr/lib/cgi-bin/metro|" \
	-e "s|^www/netmagis|usr/lib/cgi-bin/netmagis|" \
	-e "s|^%%WWWDIR%%|usr/lib/cgi-bin/netmagis|" \
	-e "s|^%%PORTEXAMPLES%%%%EXAMPLESDIR%%|usr/share/doc/netmagis/examples|" \
	$src > $dst

}

modconf()
{
    src=$1

    sed -i \
	-e "s|/etc/namedb/master|/etc/bind|" \
	-e "s|/usr/local/bin/pdflatex|/usr/bin/pdflatex|" \
	-e "s|/usr/local/bin/dot|/usr/bin/dot|" \
	-e "s|/usr/local/bin/pwgen|/usr/bin/pwgen|" \
	-e "s|/usr/local/etc/rc.d/isc-dhcpd.sh|/etc/init.d/isc-dhcpd-server|" \
	-e "s|/etc/dhcp-gen.conf|/etc/dhcp/dhcp-gen.conf|" \
	-e "s|/usr/local/sbin/dhcpd|/usr/sbin/dhcpd|" \
	-e "s|/etc/dhcpd.conf|/etc/dhcp/dhcpd.conf|" \
	-e "s|/usr/lib/rancid/bin/rancid-run|/usr/bin/rancid-run|" \
	-e "s|/usr/local/sbin/fping|/usr/bin/fping|" \
	-e "s|/usr/local/var/rancid/mygroup|/var/lib/rancid/mygroup|" \
	-e "s|/usr/local/libexec/rancid/clogin|/usr/lib/rancid/bin/clogin|" \
	-e "s|/usr/local/libexec/rancid/hlogin|/usr/lib/rancid/bin/hlogin|" \
	-e "s|/usr/local/libexec/rancid/jlogin|/usr/lib/rancid/bin/jlogin|" \
	$src
}

# Fetch the tarball
[ -f $TGZ ] || wget $URL 

# Erase package files
rm -f netmagis_${VERSION}*.orig.tar.gz netmagis-*_${VERSION}*.deb

# Create work directory
DIR=netmagis-$VERSION

rm -fr $DIR

tar xzf $TGZ

cd $DIR

# Prepare debian directory and backup orig file
dh_make -m -p netmagis_${VERSION} -f ../$TGZ </dev/null
dquilt new install.patch
dquilt add Makefile
dquilt add common/netmagis.conf.sample

(
cd ..
modmakefile $DIR/Makefile

modconf $DIR/common/netmagis.conf.sample
)

# Remove unused templates
rm -f debian/*.EX debian/*.ex

# Copy init files
tar cf - -C .. etc | tar xf - -C debian

# Copy debian files
for i in control copyright rules README.Debian
do
    sed $SUBST ../$i > debian/$i
done

# Generate install files from FreeBSD ports
for i in $PORTSDIR/netmagis-*/pkg-plist
do
    pkgname=`echo $i | sed 's|.*/\(netmagis-[a-z]*\)/pkg-plist$|\1|'`
    geninstall $i debian/$pkgname.install
done

# Add init scripts to install files (from FreeBSD ports)
# These scripts will be copied in the "build" directory by the "rules" makefile
cat >> debian/netmagis-topo.install <<EOF
etc/init.d/topographd
etc/init.d/toposendd
EOF

dquilt refresh
dquilt header
# set patch headers as per http://dep.debian.net/deps/dep3/
dquilt header -r <<EOH
Description: Changes needed to build deb packages
 Path adjustments inside Makefile and example file.
Author: $DEBFULLNAME <$DEBEMAIL>
Forwarded: not-needed
EOH
debuild -us -uc
