#!/bin/sh

#
# Create or update Debian repository
#
# Usage Example:
#
#    update-repo 2.1.0 $HOME/netmagis/pkg/debian stable /local/repo
#
#    update-repo 2.1.0b1 $HOME/netmagis/pkg/debian dev /local/repo
#
# The package reprepro is required to run this script
#
# History:
#   2012/05/16 : pda/jean : design

if [ $# -ne 4 ]
then
	echo "Usage: $0 version pkgdir distrib repodir" >&2
	exit 1
fi

VERSION="$1"
PKGDIR="$2"
DISTRIB="$3"
REPODIR="$4"

# Check for repository existence
if [ ! -d "$REPODIR" ]
then
    echo "Directory '$REPODIR' does not exist" >&2
    exit 1
fi
conffile="$REPODIR"/conf/distributions
if [ ! -f "$conffile" ]
then
    echo "File '$conffile' does not exist" >&2
    exit 1
fi

# Check for distribution
if grep -q "^Codename:[ 	]*$DISTRIB$" "$conffile"
then :
else
    echo "Distribution '$DISTRIB' not found in '$conffile'" >&2
    exit 1
fi

# Check for packages
for i in common database metro servers topo utils www 
do
    if ls $PKGDIR | grep -q "netmagis-${i}_$VERSION-.*\.deb"
    then :
    else
	echo "Package $PKGDIR/netmagis-${i}_$VERSION-*.deb not found" >&2
	exit 1
    fi
done

# Update repository
reprepro -b $REPODIR includedeb $DISTRIB $PKGDIR/netmagis-*_$VERSION-*.deb
reprepro -b $REPODIR includedsc $DISTRIB $PKGDIR/netmagis_$VERSION-*.dsc
