#!/bin/sh

#
# Create or update Debian repository
#
# Usage Example:
#
#    update-repo 2.1 $HOME/netmagis/pkg/debian /local/repo
#
# The package reprepro is required to run this script
#
# History:
#   2012/05/16 : pda/jean : design

if [ $# -ne 3 ]
then
	echo "Usage: $0 version pkgdir repodir" >&2
	exit 1
fi

VERSION="$1"
PKGDIR="$2"
REPODIR="$3"

# Check repository existence
if [ ! -d "$REPODIR" ]
then
    echo "Directory $REPODIR does not exist" >&2
    exit 1
fi


# Check for packages
for i in common database metro servers topo utils www 
do
    if ls $PKGDIR | grep -q "netmagis-${i}_$VERSION-.*\.deb"
    then :
    else
	echo "Package $PKGDIR/netmagis-${i}_$VERSION-*.deb not found" >&2
	exit 1
    fi
done

# Create configuration file for reprepro
mkdir -p $REPODIR/conf
cat > $REPODIR/conf/distributions <<EOF
Origin: netmagis
Label: netmagis
Codename: stable
Architectures: amd64 i386 source
Components: main
Description: Apt repository for netmagis
#SignWith: <key-id>
EOF

# Create or update repository
reprepro -b $REPODIR includedeb stable $PKGDIR/netmagis-*_$VERSION-*.deb
reprepro -b $REPODIR includedsc stable $PKGDIR/netmagis_$VERSION-*.dsc
