# Created by: Pierre David <pdagog@gmail.com>, Jean Benoit <jean@unistra.fr>
# $FreeBSD: head/net-mgmt/netmagis-metro/Makefile 327757 2013-09-20 22:24:43Z bapt $

PORTNAME=	netmagis
PKGNAMESUFFIX=	-metro

COMMENT=	Netmagis metrology module

MASTERDIR=	${.CURDIR}/../netmagis-common

PKGMESSAGE=	${.CURDIR}/pkg-message
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
