#!/bin/sh

# $Id: mkroutages,v 1.2 2007-08-29 10:51:47 pda Exp $

#
# Script de génération des routages de messagerie.
#
# Syntaxe :
#	aucun paramètre
#
# Historique
#   2004/04/05 : pda/jean : création
#

# Chemin complet du script de génération d'une table de routages de sendmail
GENERER=/local/sbin/generer-routages

# Programme de génération des fichiers .db utilisés par sendmail
MAKEMAP="/usr/sbin/makemap -N hash"

# Répertoire où sendmail s'attend à trouver ses "maps"
MAPSDIR=/local/mail/maps

#
# Fichiers relatifs dans le répertoire MAPSDIR
#
PROLOGUE=routages.prologue		# ajouté en tête de la table de routage
ROUTAGES=routages			# le fichier généré
OLD=$ROUTAGES.old			# la copie de l'ancien, au cas où...

#
# Fichier temporaire pour la génération du nouveau routages
#
TMP=/tmp/mkroutages.$$

#
# Vérification de la syntaxe avant d'aller plus avant.
#
if [ $# != 0 ]
then
    echo "usage: $0" >&2
    exit 1
fi

cd $MAPSDIR

#
# Génération du nouveau fichier de routages
#
rm -f $TMP
cat $PROLOGUE > $TMP && $GENERER >> $TMP
if [ $? != 0 ]
then
    echo "Erreur lors de la génération des routages. Abandon."
    exit 1
fi

if cmp $TMP $ROUTAGES > /dev/null
then :
else
    #
    # Installer le nouveau fichier
    #
    cp $ROUTAGES $OLD
    if [ $? != 0 ]
    then
	echo "Erreur lors de la sauvegarde de l'ancien routages. Abandon."
	exit 1
    fi

    mv $TMP $ROUTAGES && $MAKEMAP $ROUTAGES < $ROUTAGES
    if [ $? != 0 ]
    then
	echo "Erreur lors de l'installation des routages. Abandon."
	mv $OLD $ROUTAGES
	exit 1
    fi

    #
    # Le résultat va sur la sortie standard, et cron l'enverra par
    # mail.
    #
    diff $OLD $ROUTAGES
fi

rm -f $TMP
