#!/bin/sh

# $Id: quotidien,v 1.2 2007-08-29 10:51:47 pda Exp $

#
# Maintenance quotidienne de la base DNS
#	- sauvegarde de la base
#	- copie dans la base de developpement
#	- petit coup d'aspirateur
#
# Historique
#   2002/06/04 : pda : conception de la partie developpement
#   2002/06/19 : pda : conception de la partie sauvegarde
#   2002/07/25 : pda : fusion dans un seul et même script
#

PGUSER=pgsql
PGPASSWORD=mot-de-passe-de-dns
export PGUSER PGPASSWORD

BASE=dns
BASEDEV=devdns
DUMPDIR=/local/applis/dns/dump

PGDUMP=/usr/local/bin/pg_dump
PGRESTORE=/usr/local/bin/pg_restore
VACUUMDB=/usr/local/bin/vacuumdb

AUJOURDHUI=`date +%a`			# jour de la semaine

sauvegarde ()
{
    $PGDUMP --file $DUMPDIR/dump.$AUJOURDHUI $BASE
}

copiedev ()
{
    FILE=$DUMPDIR/dump.bin
    $PGDUMP --file=$FILE --format=c $BASE \
	&& $PGRESTORE --clean --dbname=$BASEDEV $FILE
}

vacuum ()
{
    $VACUUMDB --quiet --full $BASE
}

if sauvegarde && copiedev && vacuum
then
    exitcode=0
else
    echo "Erreur lors des opérations de maintenance de la base $BASE"
    exitcode=1
fi

exit $exitcode
