#!/bin/sh

# $Id: sauvegarde,v 1.2 2007-08-29 10:51:47 pda Exp $

#
# Maintenance horaire de la base DNS
#
# Historique
#   2004/08/04 : pda : conception
#

PGUSER=pgsql
PGPASSWORD=mot-de-passe-de-dns
export PGUSER PGPASSWORD

BASE=dns
DUMPDIR=/local/applis/dns/dump
PGDUMP=/usr/local/bin/pg_dump

MAINTENANT=`date +%a-%H`		# jour de la semaine + heure

sauvegarde ()
{
    $PGDUMP --file $DUMPDIR/dump.$MAINTENANT $BASE
}

if sauvegarde
then
    exitcode=0
else
    echo "Erreur lors de la sauvegarde de la base $BASE"
    exitcode=1
fi

exit $exitcode
