#!/bin/sh

#
# Lance rancid en affichant le résultat sur la sortie standard
# au lieu de l'envoyer par mail.
#
# Syntaxe :
#	start-rancid [eq]
#
# Historique
#   2007/07/03 : pda/jean : conception
#   2010/10/20 : pda/jean : intégration dans topo
#

# Dans le répertoire SENDMAILDIR, il y a un vrai-faux-programme sendmail
# qui envoie le resultat sur le descripteur numéro 3 (au lieu de l'envoyer
# par mail)

SENDMAILDIR=%TOPODIR%/bin

PATH=$SENDMAILDIR:$PATH
export PATH

case $# in
    0) ARGS= ;;
    1) ARGS="-r $1" ;;
    *) echo "usage: $0 [eq]" >&2 ; exit 1 ;;
esac

#
# Collecter les mails prétenduement envoyés par rancid (récupérés sur
# le descripteur 3) et les rediriger vers la sortie standard.
#

# XXX : SUPPRIMER "test" lorsque les tests seront terminés
exec %RANCIDCMD% $ARGS test 3>&1
