#!/bin/sh


#
# Remplissage des paramètres de configuration
#
# Syntaxe :
#	remplir-config
# (pas d'argument)
#
# Historique :
#   2004/04/04 : pda      : conception
#   2005/04/08 : pda      : ajout des valeurs dhcp
#

BASE=dns

PGPASSWORD="mot-de-passe-de-dns"
export PGPASSWORD

PGCLIENTENCODING="latin9"
export PGCLIENTENCODING

psql --quiet $BASE <<'EOF'
------------------------------------------------------------------------------
-- Chargement initial des paramètres de configuration
------------------------------------------------------------------------------

-- Mettez ici le ou les groupes possibles (cf WebAuth) pour les
-- utilisateurs de l'application
INSERT INTO config (clef, valeur) VALUES ('groupes', 'osiris') ;

-- A priori, ne plus rien modifier après cette valeur
INSERT INTO config (clef, valeur) VALUES ('datefmt', '%d/%m/%Y %Hh%M') ;
INSERT INTO config (clef, valeur) VALUES ('jourfmt', '%a %d %b %Y') ;
INSERT INTO config (clef, valeur) VALUES ('authmailfrom', '1') ;
INSERT INTO config (clef, valeur) VALUEs ('mailfrom', NULL) ;
INSERT INTO config (clef, valeur) VALUES ('authmailreplyto', '1') ;
INSERT INTO config (clef, valeur) VALUEs ('mailreplyto', NULL) ;
INSERT INTO config (clef, valeur) VALUES ('authmailcc', '1') ;
INSERT INTO config (clef, valeur) VALUEs ('mailcc', NULL) ;
INSERT INTO config (clef, valeur) VALUES ('authmailbcc', '1') ;
INSERT INTO config (clef, valeur) VALUEs ('mailbcc', NULL) ;
INSERT INTO config (clef, valeur) VALUES ('authmailsubject', '1') ;
INSERT INTO config (clef, valeur) VALUEs ('mailsubject', NULL) ;
INSERT INTO config (clef, valeur) VALUES ('authmailbody', '1') ;
INSERT INTO config (clef, valeur) VALUES ('mailbody', NULL) ;
INSERT INTO config (clef, valeur) VALUES ('default_lease_time', 600) ;
INSERT INTO config (clef, valeur) VALUES ('max_lease_time', 3600) ;
INSERT INTO config (clef, valeur) VALUES ('min_lease_time', 300) ;

------------------------------------------------------------------------------
-- Chargement des types de machines
------------------------------------------------------------------------------

-- L'id 0 doit $etre par défaut "Non renseigné". C'est la valeur
-- prise en compte par le script de chargement (remplir-domaine)
INSERT INTO hinfo (texte, tri, present) VALUES ('Non renseigné',      0,   0) ;
INSERT INTO hinfo (texte, tri, present) VALUES ('PC/Windows',	      10,  1) ;
INSERT INTO hinfo (texte, tri, present) VALUES ('PC/Unix',	      20,  1) ;
INSERT INTO hinfo (texte, tri, present) VALUES ('Macintosh/MacOS',    30,  1) ;
INSERT INTO hinfo (texte, tri, present) VALUES ('Autres/Unix',	      50,  1) ;
INSERT INTO hinfo (texte, tri, present) VALUES ('Imprimante',	      70,  1) ;
INSERT INTO hinfo (texte, tri, present) VALUES ('Eq. réseau',	      100, 1) ;
EOF
