#!/usr/bin/perl

use DBI;
use POSIX;
use warnings;
use strict;

require "%DESTDIR%/lib/netmagis/libmetro.pl";

# Read configuration file
our $conf_file = "%CONFFILE%";
our %global_conf = read_global_conf_file($conf_file);

# Set log parameters
set_process_name("plugin-ipmac");
set_log_facility($global_conf{pollerlogfacility});

# Parameters
my $table = "mac.ipmac";

# Open mac database
my $db =  db_connect($global_conf{'macdbname'}, $global_conf{'macdbhost'},
		$global_conf{'macdbuser'}, $global_conf{'macdbpassword'});

# Load data files
my $filepattern = "ipmac_.*";
my @filelist = lsfiles($global_conf{'metrodatadir'}. "/report/", $filepattern);
# Update sessions for each file
foreach my $file (@filelist) {
	my $src=guess_eq($file);
	my $polled_sessions = load_sessions($file);
	if($polled_sessions && $src) {
		if(update_sessions($db,$table,$src,$polled_sessions)) {
			# Suppress file when processed
			unlink($file);
		}
	}
}
