#!/usr/bin/perl

use DBI;
use POSIX;
use warnings;
use strict;

require "%DESTDIR%/lib/netmagis/libmetro.pl";

# Read configuration file
our $conf_file = "%CONFFILE%";
our %global_conf = read_global_conf_file($conf_file);

# Set log parameters
set_process_name("plugin-ipmac");
set_log_facility($global_conf{pollerlogfacility});

# Parameters
my $table = "mac.ipmac";

# Open mac database
my $db =  db_connect($global_conf{'macdbname'}, $global_conf{'macdbhost'},
		$global_conf{'macdbuser'}, $global_conf{'macdbpassword'});

my $filepattern = "ipmac_.*";
my $dir = $global_conf{'metrodatadir'}. "/report/";

# Process all session files
process_sessions($db, $table, $dir, $filepattern);
