#! /bin/sh

# PROVIDE: toposendd
# REQUIRE: DAEMON
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf to enable toposendd:
#
# toposendd_enable="YES"
#
# # Optionnal variables:
# toposendd_flags=""
# toposendd_user="rancid"
#

. /etc/rc.subr

name=toposendd
rcvar=toposendd_enable

load_rc_config $name

: ${toposendd_enable:=NO}
: ${toposendd_flags:=""}
: ${toposendd_user:="rancid"}

command="%NMLIBDIR%/topo/toposendd"

run_rc_command "$1"
