#!/bin/sh

#
# Liste de remplissage des machines d'un domaines.
#
# Un domaine est rempli à partir des informations se trouvant dans
# le fichier de zones (après le commentaire "COUPER ICI")
#
# L'ordre est important. Si un fichier de zone pour le domaine d1
# contient une référence à une information d'un domaine d2 (par exemple
# un CNAME dans d1 référençant un A dans d2), alors le remplissage de
# d2 doit être placé avant celui de d1.
#
# Un domaine peut être rempli plusieurs fois, pour le cas où il y
# aurait des références croisées (un CNAME dans le domaine d1 pointant
# sur un A dans le domaine d2, un CNAME dans d2 pointant sur un A dans
# d1).
#
# Arguments de remplir-domaine
#	- nom du domaine
#	- nom du fichier de zone correspondant
#	- nom de login d'un utilisateur
#

./remplir-domaine univ-machin.fr	zones/univ-machin.fr		pda
./remplir-domaine labo2.univ-machin.fr	zones/labo2.univ-machin.fr	pda
./remplir-domaine esiatf.fr		zones/esiatf.fr			pda
./remplir-domaine bidon.org		zones/bidon.org			pda
