#!/bin/sh

# $Id: charger-zones,v 1.2 2007-08-29 10:51:52 pda Exp $

#
# Liste de remplissage des zones
#

#./remplir-zone \
#	univ-machin.fr normal univ-machin.fr \
#	2004040401 zones/univ-machin.fr rrsup.txt 1

./remplir-zone \
	univ-machin.fr normal univ-machin.fr \
	2004040401 zones/univ-machin.fr /dev/null 1

./remplir-zone \
	labo2.univ-machin.fr normal labo2.univ-machin.fr \
	2004040401 zones/labo2.univ-machin.fr /dev/null 1

./remplir-zone \
	esiatf.fr normal esiatf.fr \
	2004040401 zones/esiatf.fr /dev/null 1

./remplir-zone \
	bidon.org normal bidon.org \
	2004040401 zones/bidon.org /dev/null 1

./remplir-zone \
	16.172.in-addr.arpa reverse-ipv4 172.16/16 \
	2004040401 zones/16.172.in-addr.arpa /dev/null 1

./remplir-zone \
	4.3.2.1.0.6.6.0.1.0.0.2.ip6.arpa reverse-ipv6 2001:660:1234::/48 \
	2004040401 zones/4.3.2.1.0.6.6.0.1.0.0.2.ip6.arpa /dev/null 1
