# New ports collection makefile for:	Netmagis
# Date created:		Nov 10 2011
# Whom:			Pierre David <pdagog@gmail.com>, Jean Benoit <jean@unistra.fr>
#
# $FreeBSD:$
#

PORTNAME=	netmagis
PKGNAMESUFFIX=	-topo

COMMENT=	Netmagis topology module

MASTERDIR=	${.CURDIR}/../netmagis-common

PKGMESSAGE=	${.CURDIR}/pkg-message
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
