# Created by: Pierre David <pdagog@gmail.com>, Jean Benoit <jean@unistra.fr>
# $FreeBSD: head/net-mgmt/netmagis-utils/Makefile 391542 2015-07-08 02:25:27Z pgollucci $

PORTNAME=	netmagis
PKGNAMESUFFIX=	-utils

COMMENT=	Netmagis command-line utilities

RUN_DEPENDS=	netmagis-config:${PORTSDIR}/net-mgmt/netmagis-common

MASTERDIR=	${.CURDIR}/../netmagis-common

NO_ARCH=	yes

PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
