# Created by: Pierre David <pdagog@gmail.com>, Jean Benoit <jean@unistra.fr>
# $FreeBSD: head/net-mgmt/netmagis-utils/Makefile 347582 2014-03-09 14:23:24Z miwi $

PORTNAME=	netmagis
PKGNAMESUFFIX=	-utils

COMMENT=	Netmagis command-line utilities

MASTERDIR=	${.CURDIR}/../netmagis-common

PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
