# Created by: Pierre David <pdagog@gmail.com>, Jean Benoit <jean@unistra.fr>
# $FreeBSD: ports/net-mgmt/netmagis-utils/Makefile,v 1.1 2012/10/30 20:35:58 crees Exp $

PORTNAME=	netmagis
PKGNAMESUFFIX=	-utils

COMMENT=	Netmagis command-line utilities

MASTERDIR=	${.CURDIR}/../netmagis-common

PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
