#!/bin/sh

#
# This script is a fake, used to collect mails sent by the true "rancid"
# program and redirect them to file descriptor 3. This avoids to mix
# with other log informations which do not interest us.
#
# History
#   2007/07/03 : pda/jean : design
#   2010/10/20 : pda/jean : topo integration
#

(
	sed '1,/^$/ {
			s/^To:.*//
			s/^Precedence:.*//
			s/^Subject: />>> /
		}'
) >&3
