#!/bin/sh

#
# This script creates a patch suitable for FreeBSD ports, to include
# in a FreeBSD PR, see https://bugs.freebsd.org/bugzilla/enter_bug.cgi
#
# It assumes that:
# - the working directory is: netmagis/pkg/freebsd
# - some ports are loaded
#	ports-mgmt/portlint ports-mgmt/porttools
# - 
#

PORTSDIR=/usr/ports
CATEGORY=$PORTSDIR/net-mgmt
OUTPUT=/tmp/netmagis

PORTLIST="
	netmagis-common
	netmagis-database
	netmagis-detecteq
	netmagis-metro
	netmagis-servers
	netmagis-topo
	netmagis-utils
	netmagis-www
	"

HERE=$(pwd)

init ()
{
    cd $PORTSDIR
    svn update || exit 1

    cd $CATEGORY
    for p in $PORTLIST
    do
	if [ -d $p.old ]
	then
	    (
		echo "$p.old exists in $PORTSDIR."
		echo "Use '$0 finish' before a new run."
		echo "Stop"
	    ) >&2
	    exit 1
	fi
	mv $p $p.old && tar cf - -C $HERE $p | tar xf -
    done
}

#
# Distfile fetch && sum
#

sum ()
{
    rm -f $PORTSDIR/distfile/netmagis-*
    cd $CATEGORY/netmagis-common
    make makesum
}

#
# Portlint
#

test_portlint ()
{
    for p in $PORTLIST
    do
	cd $CATEGORY/$p
	echo "================> $p"
	portlint -AC
    done
}

#
# Port test
#

test_porttest ()
{
    for p in $PORTLIST
    do
	echo "================> $p"
	port test $CATEGORY/$p
    done
}

#
# Run configure in order to avoid user interaction during test_make
#

make_config ()
{
    for p in $PORTLIST
    do
	cd $CATEGORY/$p
	sudo make config-conditional
    done
}

#
# Make stage & co
#

test_make ()
{
    for p in $PORTLIST
    do
	cd $CATEGORY/$p
	echo "================> $p"
	sudo make stage &&
	    sudo make check-plist &&
	    sudo make stage-qa &&
	    sudo make package &&
	    sudo make clean
    done 2>&1
}

#
# Get svn diff
#

svndiff ()
{
    cd $PORTSDIR
    svn diff
}

#
# Remove new ports
#

finish ()
{
    cd $CATEGORY
    for p in $PORTLIST
    do
	rm -rf $p && mv $p.old $p
    done
}

if [ $# -eq 0 ]
then
    set init sum portlint porttest config make diff finish
fi

for action
do
    case "$action" in
	init)		init ;;
	sum)		sum ;;
	portlint)	test_portlint	> $OUTPUT.portlint ;;
	porttest)	test_porttest	> $OUTPUT.porttest ;;
	config)		make_config ;;
	make)		test_make	> $OUTPUT.make ;;
	diff)		svndiff		> $OUTPUT.diff ;;
	finish)		finish ;;
	*)
	    echo "usage: $0 [init|portlint|porttest|make|diff|finish] ..." >&2
	    exit 1
	    ;;
    esac
done
