
#
# Netmagis translation messages
#

###############################################################################
# Links menu
::msgcat::mcmset fr {
 {%1$s available addresses / %2$s total} {%1$s adresses disponibles / %2$s total}
 {'%1$s' has been removed from view '%2$s'} {'%1$s' a été supprimé de la vue '%2$s'}
 {'%1$s' has IP addresses in view '%2$s'} {'%1$s' a des adresses IP dans la vue '%2$s'}
 {%1$s in view %2$s is a mail address hosted by %3$s in view %4$s} {%1$s dans la vue %2$s est une adresse de messagerie hébergée par %3$s dans la vue %4$s}
 {%1$s is a host in view %2$s} {%1$s est une machine dans la vue %2$s}
 {%1$s is an alias of host %2$s in view %3$s} {%1$s est un alias de la machine %2$s dans la vue %3$s}
 {'%1$s' is not a mail role in view '%2$s'} {'%1$s' n'est pas un rôle de messagerie dans la vue '%2$s'}
 {'%1$s' is not a valid IPv%2$s address} {'%1$s' n'est pas une adresse IPv%2$s valide}
 {%1$s MAC-IP address associations found for %2$s:} {%1$s associations IP-MAC trouvées pour %2$s :}
 {%1$s Regular expression %2$s Phonetic} {%1$s Exp. régulière %2$s Phonétique}
 {Access denied to view '%s'} {Accès refusé à la vue '%s'}
 {Access denied to IP address '%s'} {Accès refusé à l'adresse IP '%s'}
 {Account has been removed from realms: %s} {Le compte a été supprimé des royaumes ci-après : %s}
 {Account is still active in authentication subsystem} {Le compte reste toutefois actif dans le sous-système d'authentification}
 {Account '%s' insertion} {d'ajout du compte '%s'}
 {Account '%s' modification} {de modification du compte '%s'}
 {ACL management} {Gestion des ACL}
 {Action} {Action}
 {active} {activé}
 {Add account} {Ajouter compte}
 {Add} {Ajouter}
 {Addition or RR '%1$s' failed: %2$s} {Ajout du RR '%1$s' impossible : %2$s}
 {Add realm} {Ajouter royaume}
 {Address %1$s matches %2$s in view '%3$s'} {L'adresse %1$s correspond à %2$s dans la vue '%3$s'}
 {Address}	{Adresse}
 {address not allowed} {adresse non accessible}
 {Address '%s' not found} {Adresse '%s' non trouvée}
 {add %s} {ajout de %s}
 {Addtl RR}	{RR suppl.}
 {Admin} {Admin}
 {<a href="%1$s">Edit informations</a> of '%2$s'} {<a href="%1$s">Éditer les informations</a> de '%2$s'}
 {<a href="%1$s">Modify '%2$s'</a> in view '%3$s'} {<a href="%1$s">Modifier '%2$s'</a> dans la vue '%3$s'}
 {<a href="%1$s">Remove address '%2$s'</a> from '%3$s' (all other addresses of this host will stay)} {<a href="%1$s">Supprimer l'adresse '%2$s'</a> de '%3$s' (mais il restera les autres adresses)}
 {<a href="%1$s">Remove</a> host '%2$s'} {<a href="%1$s">Supprimer</a> la machine '%2$s'}
 {alias} {alias}
 {Aliases}		{Aliases}
 {Alias name}	{Nom de l'alias}
 {Allocated addresses} {Adresses allouées}
 {'Allow' permission '%s' outside any allowed network} {Le droit 'allow' '%s' est en dehors de tout réseau autorisé}
 {Allowed groups} {Groupes autorisés}
 {All} {Tous}
 {and sorted by '%1$s' and by '%2$s'} {et triés par '%1$s' et par '%2$s'}
 {Application parameters} {Modif paramètres}
 {assoc} {assoc}
 {auth} {auth}
 {Authentication base problem: %s} {Problème dans la base d'authentification : %s}
 {authorized special characters: -+/()&.:#_} {caractères spéciaux autorisés : -+/()&.:#_}
 {available address in all views} {adresse disponible dans toutes les vues}
 {Block account '%s'} {de blocage du compte '%s'}
 {Cannot create group of orphaned users (%s)} {Impossible de créer le groupe des utilisateurs orphelins (%s)}
 {Cannot fetch key '%1$s': %2$s} {Impossible de lire la clef '%1$s' : %2$s}
 {Cannot find registered CGI action} {Aucune action CGI trouvée}
 {Cannot lock database: %s} {Verrouillage impossible : %s}
 {Cannot lock table(s) %1$s: %2$s} {Verrouillage impossible pour la/les table(s) %1$s : %2$s}
 {Cannot open file '%1$s': %2$s} {Impossible d'ouvrir le fichier '%1$s' : %2$s}
 {Cannot perform operation "%1$s": %2$s} {Opération "%1$s" impossible : %2$s}
 {Cannot register authentication token (%s)} {Impossible d'enregistrer le token d'authentification (%s)}
 {Cannot read host-id %s} {Impossible de lire la machine d'identificateur %s}
 {Cannot read sensor list: %s} {Impossible de lire les points de collecte : %s}
 {Cannot set key '%1$s' to '%2$s: %3$s} {Impossible de modifier la clef '%1$s' à '%2$s' : %3$s}
 {Cannot write zone prologue: %s} {Impossible de modifier le prologue de la zone : %s}
 {Can't modify link %s (%s)} {Impossible de modifier le lien %s (%s)}
 {Can't reuse link %s (%s)} {Impossible de réutiliser le lien %s (%s)}
 {Change account password} {Changer mot de passe d'un compte}
 {Change log of '%1$s' at %2$s} {Log des modifications de '%1$s' au %2$s}
 {Change}	{Modification}
 {Change of '%s' not yet processed} {Modification de '%s' non encore effectuée}
 {Changes currently processed:} {Modification(s) en cours de traitement :}
 {channel %1$s power %2$s mW}	{canal %1$s puissance %2$s mW}
 {Choose the first address} {Choisir la première adresse}
 {Choose these %s addresses} {Choisir ces %s adresses}
 {Choose the %s first addresses} {Choisir les %s premières adresses}
 {Choose this address} {Choisir cette adresse}
 {CIDR matches '%s'} {CIDR correspond à '%s'}
 {Command} {Commande}
 {Comment}	{Infos complémentaires}
 {Community}	{Commaunauté}
 {Community} {Communauté}
 {Community id '%s' not found} {La communauté d'id '%s' n'est pas trouvée}
 {Community management} {Gestion des communautés}
 {community = %s} {communauté = %s}
 {Configuration commands management} {Gestion des commandes de configuration}
 {Conflict between dynamic range [%1$s] and %2$s IP address(es) declared with a MAC address} {Conflit entre l'intervalle dynamique [%1$s] et %2$s adresse(s) IP déclée(s) avec une adresse MAC}
 {Consult} {Consulter}
 {Create a new account} {Créer un nouveau compte}
 {created} {créée}
 {Create group...} {Créer un groupe...}
 {Creation} {Création}
 {creation of group %s} {création du groupe %s}
 {Criterion}	{Critère}
 {Database schema is too old. See http://netmagis.org/upgrade.html} {Le schéma de base de données est trop ancien. Consultez http://netmagis.org/upgrade.html}
 {Database schema '%1$s' is not yet recognized by Netmagis %2$s} {Le schéma de base de données '%1$s' n'est pas encore reconnu par Netmagis %2$s}
 {Date}		{Date}
 {Date sent}	{Date d'envoi}
 {deactivated interface} {interface désactivée}
 {Declared addresses (IPv4+IPv6) in view '%1$s': %2$s} {Adresses déclarées (IPv4+IPv6) dans la vue '%1$s' : %2$s}
 {declared address in at least one view} {adresse déclarée dans au moins une vue}
 {declared address, within a DHCP range} {adresse déclarée, figurant dans un intervalle DHCP}
 {Declared hosts} {Machines déclarées}
 {Default lease duration} {Durée par défaut du bail}
 {Default_lease_time value less than '%s'} {Valeur default_lease_time inférieure à '%s'}
 {(default zone value)} {(valeur par défaut de la zone)}
 {deleted} {supprimée}
 {delete %s} {suppression de %s}
 {Delete} {Supprimer}
 {Deletion of RR '%1$s' failed: %2$s} {Suppression du RR '%1$s' impossible : %2$s}
 {description} {description}
 {Description} {Description}
 {Description}	{Description}
 {description='%s'} {description='%s'}
 {detail/AP} {détail/AP}
 {Detail assoc} {Détail assoc}
 {Detail auth} {Détail auth}
 {Detail} {Détail}
 {Details} {Détails}
 {detail/SSID} {détail/SSID}
 {develop} {tout dérouler}
 {dhcpd.conf configuration}	{Directives dhcpd.conf}
 {DHCP enabled}	{DHCP activé}
 {DHCP management} {Gestion DHCP}
 {DHCP profile management} {Gestion des profils DHCP}
 {DHCP profile} {Profil DHCP}
 {DHCP profile}	{Profil DHCP}
 {DHCP ranges} {Plages DHCP}
 {Divergent sensor types} {Types de points de collecte divergents}
 {DNS/DHCP} {DNS/DHCP}
 {Domain}	{Domaine}
 {Domain-id '%s' not found} {Identificateur de domaine '%s' non trouvé}
 {Domain management} {Gestion des domaines}
 {Domain '%s' not found} {Domaine '%s' non trouvé}
 {Down} {Inactif}
 {Edit interface %1$s on %2$s} {Modification de l'interface %1$s sur %2$s}
 {Edit interfaces} {Modifier les interfaces}
 {Edit interfaces on %s} {Modification des interfaces de %s}
 {Edition of group '%s'} {Édition du groupe '%s'}
 {Edit} {Modifier}
 {Edit} {Modifier}
 {Empty group (no user)} {Groupe vide (sans utilisateur)}
 {End} {Fin}
 {envelop} {tout enrouler}
 {Equipment} {Équipement}
 {Equipment management} {Gestion des équipements}
 {equipments} {équipements}
 {Equipments} {Équipements}
 {Equipment '%s' not found} {Équipement '%s' non trouvé}
 {Equipment type management} {Gestion des types d'équipement}
 {Error accessing database: %s} {Erreur d'accès à la base de données : %s}
 {Error adding '%1$s' (%2$s)} {Erreur dans l'ajout de '%1$s': %2$s}
 {Error deleting '%1$s' (%2$s)} {Erreur dans la suppression de '%1$s' (%2$s)}
 {Error detected in view '%1$s': %2$s} {Erreur détectée dans la vue '%1$s' : %2$s}
 {Error during extraction of readable interfaces from '%1$s': %2$s} {Erreur lors de l'extraction des interfaces consultables de '%1$s' : %2$s}
 {Error during extraction of writable interfaces from '%1$s': %2$s} {Erreur lors de l'extraction des interfaces modifiables de '%1$s' : %2$s}
 {Error during spool insertion: %s} {Ajout dans la file d'attente impossible : %s}
 {ERROR}	{ERREUR}
 {Error generating graph: '%s'} {Erreur lors de la génération du graphe : %s}
 {Error in CIDR '%1$s': %2$s} {Erreur dans le CIDR '%1$s' : %2$s}
 {Error modifying '%1$s' (%2$s)} {Erreur dans la modification de '%1$s' (%2$s)}
 {Error on group permissions} {Erreur sur les droits du groupe}
 {Error while generating a link number} {Erreur dans la génération d'un numéro de lien}
 {Error while reading equipments: %s} {Erreur lors de la lecture des équipements : %s}
 {Error while reading networks: %s} {Erreur lors de la lecture des réseaux : %s}
 {Error while reading Vlans: %s} {Erreur lors de la lecture des Vlans : %s}
 {Error while reading wifi sensors: %s} {Erreur lors de la lecture des sondes Wifi : %s}
 {Error while removing realms %1$s: %2$s} {Erreur lors de la suppression des royaumes %1$s : %2$s}
 {Fax}	{Fax}
 {First available IP address} {Première adresse IP disponible}
 {First name}	{Prénom}
 {(for all views)} {(pour toutes les vues)}
 {force generation for zone %s} {forçage de la génération de la zone %s}
 {Force zone generation} {Forcer zones}
 {(for the selected view)} {(pour la vue sélectionnée)}
 {Found more than one entry for login '%s' in the authentication base} {Plus d'une entrée trouvée pour le login '%s' dans la base d'authentification}
 {General} {Général}
 {Graph currenty re-builded. Informations presented here are not necessarily consistent with current equipement configuration.} {Reconstruction du graphe en cours. Les informations fournies ne sont pas forcément cohérentes avec la configuration actuelle des équipements.}
 {Graphviz node attributes for equipments} {Attributs des noeuds Graphviz pour les équipements}
 {Group}	{Groupe}
 {Group has access to DHCP profile '%s' which do not exist in the database} {Le groupe a accès au profil '%s' qui n'existe pas dans la base}
 {Group has access to domain '%s' which do not exists in database} {Le groupe a accès au domaine '%s' qui n'existe pas dans la base}
 {Group has access to network '%s' which do not exists in database} {Le groupe a accès au réseau '%s' qui n'existe pas dans la base}
 {Group has access to view '%s' which do not exists in database} {Le groupe a accès à la vue '%s' qui n'existe pas dans la base}
 {Group has access to vlan '%s' which does not exist in the database} {Le groupe a accès au vlan '%s' qui n'existe pas dans la base}
 {Group '%s' already exist} {Le groupe '%s' existe déjà}
 {Group '%s' not found} {Groupe '%s' non trouvé}
 {Host id %s not found} {Machine d'id %s non trouvée}
 {host information} {informations de la machine}
 {Host '%s' already exists} {La machine '%s' existe déjà}
 {host %s} {la machine %s}
 {Host type management} {Gestion des types de machines}
 {Host type '%s' not found} {Type de machine '%s' non trouvé}
 {Host type}	{Type de machine}
 {Id} {Identifiant}
 {Impossible to use MAC address '%1$s' because IP address '%2$s' is in DHCP dynamic range [%3$s..%4$s]} {Impossible d'affecter l'adresse MAC '%1$s' car l'adresse IP '%2$s' figure dans l'intervalle DHCP dynamique [%3$s..%4$s]}
 {Inactive addresses} {Adresses inactives}
 {inactive} {désactivé}
 {Inactive hosts in network %1$s since more than %2$s months: } {Machines inactives dans le réseau %1$s depuis plus de %2$s mois : }
 {Inconsistency in access rights for following interfaces: %s} {Incohérence sur les droits d'accès pour les interfaces suivantes : %s}
 {Inconsistent permissions on interfaces: %s} {Droits d'accès incohérents pour les interfaces : %s}
 {(in seconds)} {(en secondes)}
 {Interface '%1$s' not found on %2$s} {L'interface '%1$s' n'est pas trouvée sur %2$s}
 {Interface}	{Interface}
 {Interfaces} {Interfaces}
 {Internal Auth} {Authentification interne}
 {Internal error for '%1$s': avail=%2$s} {Erreur interne pour '%1$s' : avail=%2$s}
 {Internal error: group '%s' not found} {Erreur interne : groupe '%s' non trouvé}
 {Internal error: id '%s' doesn't exists for a mail host} {Erreur interne : hébergeur d'id '%s' inexistant}
 {Internal error: invalid 'action' value (%s)} {Erreur interne : valeur '%s' invalide pour l'action}
 {Internal error: invalid context '%s'} {Erreur interne : contexte '%s' invalide}
 {Internal error: invalid extractcoll output format} {Erreur interne : format de sortie de extractcoll non valide}
 {Internal error: invalid key type '%s'} {Erreur interne : type de clef invalide '%s'}
 {Internal error: invalid parameter '%1$s' for '%2$s'} {Erreur interne : paramètre invalide '%$1s' pour '%2$s'}
 {Internal error: invalid parameter type '%s'} {Erreur interne : type de paramètre invalide '%s'}
 {Internal error: invalid tabular specification} {Erreur interne : spécification de tableau invalide}
 {Internal error: Netmagis version number '%s' unrecognized} {Erreur interne : numéro de version de Netmagis '%s' non reconnue}
 {Internal error: rr_mx table references RR '%s', not found in the rr table} {Erreur interne : table rr_mx référence le RR '%s', non trouvé dans la table rr}
 {Internal error: '%s' inserted, but not found in database} {Erreur interne : '%s' inséré, mais non retrouvé dans la base}
 {Internal error: too many CIDR found} {Erreur interne : trop de CIDR trouvés}
 {Internal error: unknown type} {Erreur interne : type inconnu}
 {Invalid ACL permission '%s'} {Droit ACL invalide '%s'}
 {Invalid address count '%s'} {Nombre '%s' d'adresses invalide}
 {Invalid argument '%s'} {Argument '%s' invalide}
 {Invalid character in password} {Caractère invalide dans le mot de passe}
 {Invalid CIDR '%s'} {CIDR '%s' incorrect}
 {Invalid date or time '%1$s/%2$s'} {Date ou heure invalide '%1$s/%2$s'}
 {Invalid date '%s'} {Date '%s' invalide}
 {Invalid default_lease_time value '%s'} {Valeur default_lease_time '%s' invalide}
 {Invalid DHCP permission '%s'} {Droit DHCP invalide '%s'}
 {Invalid DHCP profile sort class '%s'} {Classe de tri de profil DHCP '%s' invalide}
 {Invalid DHCP profile '%s'} {Profil DHCP '%s' invalide}
 {Invalid domain '%s'}	{Domaine '%s' invalide}
 {Invalid domain sort class '%s'} {Classe de tri de domaine '%s' invalide}
 {Invalid format '%s'} {Format '%s' invalide}
 {Invalid form values (%s)} {Valeurs de formulaire invalides (%s)}
 {Invalid FQDN '%s'}	{FQDN '%s' invalide}
 {Invalid graph size '%s'} {Taille du graphe invalide '%s'}
 {Invalid group name '%s' (allowed chars: letters, digits and minus symbol)} {Nom de groupe '%s' invalide (caractères autorisés : lettres, chiffres et caractère moins)}
 {Invalid HINFO attribute '%s'} {Attribut HINFO '%s' invalide}
 {Invalid input} {Données invalides}
 {Invalid input '%s'} {Données invalides '%s'}
 {<invalid>} {<invalide>}
 {Invalid link number (%s)} {Numéro de lien invalide (%s)} 
 {Invalid login syntax (^[a-z][-a-z0-9\.]*$)} {Syntaxe invalide pour le login ^[a-z][-a-z0-9\.]*$}
 {Invalid mail address, password is not modified} {Adresse mail invalide, mot de passe non modifié}
 {Invalid mail role '%s'} {Role mail invalide '%s'}
 {Invalid max_lease_time value '%s'} {Valeur max_lease_time '%s' invalide}
 {Invalid MX priority '%1$s' for '%2$s'} {Priorité de MX non valide '%1$s' pour '%2$s'}
 {Invalid name '%s'}	{Nom '%s' invalide}
 {Invalid network id '%s'} {Plage réseau '%s' invalide}
 {Invalid network sort class '%s'} {Classe de tri de réseau '%s' invalide}
 {Invalid node type '%1$s' for %2$s} {Type de noeud '%1$s' invalide pour %2$s}
 {Invalid occurrence '%s'} {Occurrence '%s' invalide}
 {Invalid period '%s'} {Période '%s' invalide}
 {Invalid realm '%s'} {Royaume '%s' invalide}
 {Invalid realm syntax (^[a-z][-a-z0-9]*$)} {Syntaxe invalide pour le royaume (^[a-z][-a-z0-9]*$)}
 {Invalid regular expression pattern '%s'} {Motif d'expression régulière '%s' invalide}
 {Invalid router instance '%s'} {Instance de routage '%s' invalide}
 {Invalid search operator '%s'} {Opérateur de recherche '%s' invalide}
 {Invalid search query '%s'} {Requête '%s' invalide}
 {Invalid search string '%s'} {Châine de recherche '%s' incorrecte}
 {Invalid selection mode '%s'} {Mode de sélection invalide '%s'}
 {Invalid sensor name '%s' (should be M...)} {Nom de sonde '%s' invalide (devrait être M...)}
 {Invalid SMTP emit right (must be 0 or 1)} {Droit SMTP invalide (doit être 0 ou 1)}
 {Invalid syntax for IP address '%s'} {Syntaxe invalide pour l'adresse IP '%s'}
 {Invalid syntax for MAC address '%s'} {Syntaxe invalide pour l'adresse MAC '%s'}
 {Invalid syntax '%s' for DHCP profile} {Syntaxe invalide pour le profil DHCP '%s'}
 {Invalid TTL: must be a positive integer} {TTL invalide : doit être un nombre entier positif}
 {Invalid TTL: must be less than %s} {TTL invalide : doit être inférieur à %s}
 {Invalid value '%1$s' for form variable '%2$s'} {Valeur '%1$s' invalide pour le champ de formulaire '%2$s'}
 {Invalid value '%s' for allow/deny} {Valeur '%s' incorrecte pour allow/deny}
 {Invalid value '%s' for read/write} {Valeur '%s' incorrecte pour read/write}
 {Invalid view sort class '%s'} {Classe de tri de vue '%s' invalide}
 {Invalid view '%s'}	{Vue '%s' invalide}
 {Invalid VLAN '%s'} {Vlan '%s' invalide}
 {IP address '%s' already exists} {L'adresse '%s' existe déjà}
 {IP address}	{Adresse IP}
 {IP addresses}	{Adresses IP}
 {IP address %s} {l'adresse IP %s}
 {IP-MAC association (%1$s,%2$s) not found} {Association IP-MAC (%1$s,%2$s) non trouvée}
 {IP networks} {réseaux IP}
 {IPv4 address} {Adresse IPv4}
 {IPv4 address map} {Carte des adresses IPv4}
 {IPv4 gateway} {Passerelle IPv4}
 {IPv4}		{IPv4}
 {IPv6 address} {Adresse IPv6}
 {IPv6 gateway} {Passerelle IPv6}
 {IPv6}		{IPv6}
 {L2-only networks} {Réseaux de niveau 2}
 {Last full-rancid} {Dernier full-rancid}
 {Last message for '%1$s' at %2$s} {Dernier message pour '%1$s' au %2$s}
 {Last occurrence} {Dernière occurrence}
 {Last processed equipments} {Derniers équipements traités}
 {Link number} {Numéro de lien}
 {List accounts} {Lister comptes}
 {List MX} {Lister MX}
 {List networks} {Lister réseaux}
 {List of declared addresses} {Liste des adresses déclarées}
 {List of networks filtered by: } {Liste des réseaux filtrés par : }
 {List of users} {Liste des utilisateurs}
 {List realms} {Lister royaumes}
 {List users} {Lister correspondants}
 {location} {localisation}
 {location}	{localisation}
 {Location}	{Localisation}
 {Logged as %s} {Connecté comme %s}
 {Login '%1$s' already assigned to group '%2$s'} {Login '%1$s' déjà affecté au groupe '%2$s'}
 {Login}	{Login}
 {Login '%s' already exists} {Le login '%s' existe déjà}
 {Login '%s' does not exist} {Le login '%s' n'existe pas}
 {Login '%s' found more than once} {Le login '%s' est ambigu}
 {Login failed} {Échec d'authentification}
 {Logout successful} {Déconnexion réussie}
 {Log}		{Log}
 {MAC address}	{Adresse MAC}
 {MAC address %s} {l'adresse MAC %s}
 {MAC index} {Accueil MAC}
 {Mac} {Mac}
 {MAC module access} {Accès au module MAC}
 {MAC search} {Recherche MAC}
 {MAC stats} {Stats MAC}
 {Mail address} {Adresse de messagerie}
 {Mail addresses} {Adresses de messagerie}
 {Mailbox host} {Hébergeur des boîtes}
 {Mail}	{Mél}
 {Mail relays deleted} {Relais de messagerie supprimés}
 {mail relays} {relais de messagerie}
 {Mail role edition} {Édition des rôles de messagerie}
 {Mail role management} {Édition des rôles de messagerie}
 {mail role} {rôle de messagerie}
 {Mail roles} {Rôles mail}
 {Maximum lease duration} {Durée maximum du bail}
 {Max_lease_time value less than '%s'} {Valeur max_lease_time inférieure à '%s'}
 {Max}		{Max}
 {Method}	{Méthode}
 {Min}		{Min}
 {Mobile}	{Tél mobile}
 {Model} {Modèle}
 {Modification} {Modification}
 {modification of group %s} {modification du groupe %s}
 {Modified equipments} {Équipements modifiés}
 {modified} {modifiée}
 {Modify account} {Modifier compte}
 {Modify communities} {Modif communautés}
 {Modify configuration commands} {Modif commandes de configuration}
 {Modify DHCP profiles} {Modif profils DHCP}
 {Modify domains} {Modif domaines}
 {Modify equipments} {Modif équipements}
 {Modify equipment types} {Modif types d'équipement}
 {Modify Graphviz attributes} {Modif attributs Graphviz}
 {Modify group name or erase it to remove the group} {Modifiez le nom du groupe ou effacez-le pour supprimer le groupe}
 {Modify machine types} {Modif types de machines}
 {Modify mailhost} {Modif relais de messagerie}
 {Modify} {Modifier}
 {Modify MX} {Modif MX}
 {Modify networks} {Modif réseaux}
 {Modify organizations} {Modif établissements}
 {Modify realm} {Modifier royaume}
 {Modify reverse IPv4 zones} {Modif zones IPv4}
 {Modify reverse IPv6 zones} {Modif zones IPv6}
 {modify %s} {modification de %s}
 {Modify users and groups} {Modif groupes}
 {Modify views} {Modif vues}
 {Modify Vlans} {Modif Vlans}
 {Modify zones} {Modif zones normales}
 {More than 6 months} {Plus de 6 mois}
 {More than 9 months} {Plus de 9 mois}
 {More than one year} {Plus d'un an}
 {MX '%1$s' points to a domain on which you don't have rights\n%2$s} {Le MX '%1$s' référence un domaine auquel vous n'avez pas accès\n%2$s}
 {MX}		{MX}
 {Name '%1$s' is not a host in view '%2$s'} {Le nom '%1$s' ne correspond pas à une machine dans la vue '%2$s'}
 {Name and aliases} {Noms et aliases}
 {Name}		{Nom}
 {Name '%s' does not exist} {Le nom '%s' n'existe pas}
 {native vlan} {vlan natif}
 {Netmagis administration} {Administration de Netmagis}
 {Network management} {Gestion des réseaux}
 {Network '%s' is not DHCP enabled} {Le réseau '%s' n'a pas la capacité DHCP}
 {Network '%s'} {Réseau '%s'}
 {networks} {réseaux}
 {Networks} {Réseaux}
 {(never)} {(jamais)}
 {New group creation} {Création d'un nouveau groupe}
 {new mail relays} {nouveaux relais de messagerie}
 {No access: %s} {Accès impossible: %s}
 {No account found} {Aucun compte trouvé}
 {No allowed DHCP profile} {Aucun profil DHCP autorisé}
 {No allowed domain} {Aucun domaine autorisé}
 {No allowed network} {Aucun réseau autorisé}
 {No allowed view} {Aucune vue autorisée}
 {No allowed L2-only network} {Aucun réseau de niveau 2 autorisé}
 {No 'allow' permission found for network '%s'} {Aucun droit 'allow' trouvé pour le réseau '%s}
 {No authorized network} {Aucun réseau autorisé}
 {No block of %s free IPv4 address(es) found} {Aucun bloc de %s adresse(s) trouvé}
 {(no date)} {(aucune date)}
 {no description} {pas de description}
 {No difference. Zone '%s' not modified} {Aucune différence. Zone '%s' non modifiée}
 {No equipment address} {Pas d'adresse d'équipement}
 {No equipment found} {Aucun équipement trouvé}
 { (no filter) } { (aucun filtre) }
 {no inactive host found} {aucune machine inactive trouvée}
 {No information found} {Aucune information trouvée}
 {No IP-MAC association found} {Aucune association IP-MAC trouvée}
 {No login: authentication failed} {Pas de login : l'authentification a échoué}
 {No MAC-IP address association found for %s} {Aucune association IP-MAC trouvée pour %s}
 {No MAC-Port-VLAN association found} {Aucune association adresse MAC-Port-VLAN trouvée}
 {No mail role found for '%s'} {Aucun rôle de messagerie trouvé pour '%s'}
 {No message for '%s'} {Aucun message pour '%s'}
 {No message from anaconf} {Aucun message provenant d'anaconf}
 {(no MX for this domain)} {(pas de MX pour ce domaine)}
 {No MX given for %s} {Pas de MX fourni pour %s}
 {non-declared address within a DHCP range} {adresse non déclarée, figurant dans un intervalle DHCP}
 {(none)}	{(aucune)}
 {None (it's ok)} {Aucun (tout va bien)}
 {Non-existent link number (%s)} {Numéro de lien inexistant (%s)}
 {no}		{non}
 {No}		{Non}
 {No permission} {Aucun droit}
 {No profile} {Aucun profil}
 {No selected domain} {Aucun domaine sélectionné}
 {No selected network} {Aucun réseau sélectionné}
 {No selected view} {Aucune vue sélectionnée}
 {No sensor selected} {Aucun point de collecte sélectionné}
 {No valid CIDR: %s} {Aucun CIDR valide : %s}
 {Not connected} {Non connecté}
 {Number of associated hosts on %s} {Nombre de machines associées sur %s}
 {Number of associated hosts on ssid %1$s of interface %2$s of %3$s} {Nombre de machines associées sur le ssid %1$s de l'interface %2$s de %3$s}
 {Number of auhentified users on %s} {Nombre d'utilisateurs authentifiés sur %s}
 {Number of auhentified users on ssid %1$s of interface %2$s of %3$s} {Nombre d'utilisateurs authentifiés sur le ssid %1$s de l'interface %2$s de %3$s}
 {Number of distinct MAC addresses associated with an IPv6 address} {Nombre d'adresses MAC distinctes associées à une adresse IPv6}
 {Number of unique IPv4 addresses} {Nombre d'adresses IPv4 uniques}
 {Number of unique IPv6 addresses} {Nombre d'adresses IPv6 uniques}
 {Number of unique MAC addresses} {Nombre d'adresses MAC uniques}
 {old mail relays} {anciens relais de messagerie}
 {old MX} {anciens MX}
 {Organization id '%s' not found} {L'organisme d'id '%s' n'est pas trouvé}
 {Organization management} {Gestion des organismes}
 {Organization} {Organisme}
 {organization = %s} {organisme = %s}
 { or } { ou }
 {parameters} {paramètres}
 {Password change for '%s'} {de changement de mot de passe pour '%s'}
 {Password generation (%1$s) for %2$s} {de génération de mot de passe (%1$s) pour %2$s}
 {Password has been sent by mail} {Le mot de passe a été envoyé par mail}
 {Password mismatch} {Les mots de passe ne concordent pas}
 {Password} {Mot de passe}
 {Password to short (< %s characters)} {Mot de passe trop court (< %s caractères)}
 {Percentage} {Pourcentage}
 {Permissions} {Droits}
 {Permissions not associated with any network} {Droits non rattachés à des réseaux}
 {Phone}	{Tél fixe}
 {Points to}	{Pointe vers}
 {Present}	{Présent}
 {Print accounts} {Imprimer comptes}
 {Priority}	{Priorité}
 {Processed} {Traité}
 {Prolog}	{Prologue}
 {Range [%1$s] intersects with range [%2$s]} {L'intervalle [%1$s] a une intersection non nulle avec l'intervalle [%2$s]}
 {Range} {Plage}
 {Range [%s] not authorized} {Intervalle [%s] non autorisé}
 {Rank} {Rang}
 {Read} {Lecture}
 {Realm '%1$s' holds %2$s member(s). Delete them first} {Le groupe '%1$s' contient %2$s membre(s). Supprimez-les d'abord}
 {Realm}	{Royaume}
 {Realm '%s' insertion} {d'insertion du royaume '%s'}
 {Realm '%s' modification} {de modification du royaume '%s'}
 {Realm '%s' not found} {Royaume '%s' non trouvé}
 {Realm '%s' removal} {de suppression du royaume '%s'}
 {Realms}	{Royaumes}
 {Relay insertion failed: %s} {Insertion du relais impossible : %s}
 {Remove account} {Supprimer compte}
 {Remove alias '%s'} {Supprimer l'alias '%s'}
 {Remove host '%s'} {Supprimer la machine '%s'}
 {Remove IP address '%1$s' from host '%2$s'} {Supprimer l'adresse '%1$s' de la machine '%2$s'}
 {Remove realm} {Supprimer royaume}
 {Remove '%s' from application} {de suppression de '%s' de l'application}
 {rename %s} {renommage de %s}
 {Reset} {Réinitialiser}
 {Responsible (mail)}	{Responsable (mél)}
 {Responsible (name)}	{Responsable (nom + prénom)}
 {Responsible}	{Responsable}
 {Return to application parameter modification} {Revenir à la modification des paramètres de l'application}
 {Return to community modification} {Revenir à la modification des communautés}
 {Return to DHCP profile modification} {Revenir à la modification des profils DHCP}
 {Return to domain modification} {Revenir à la modification des domaines}
 {Return to equipment modification} {Revenir à la modification des équipements}
 {Return to equipment type modification} {Revenir à la modification des types d'équipement}
 {Return to Graphviz nodes attributes} {Revenir aux attributs des noeuds Graphviz}
 {Return to host information modification} {Revenir à la modification des types de machines}
 {Return to modification of configuration commands} {Revenir à la modification des commandes de configuration}
 {Return to network modification} {Revenir à la modification des réseaux}
 {Return to organization modification} {Revenir à la modification des organismes}
 {Return to view modification} {Revenir à la modification des vues}
 {Return to Vlan modification} {Revenir à la modification des Vlans}
 {Return to zone modification} {Revenir à la modification des zones}
 {RR addition impossible: %s} {Création du RR impossible : %s}
 {RR count} {Nombre de RR}
 {RR deleted} {RR supprimé}
 {RR}		{RR}
 {RR update impossible: %s} {Mise à jour du RR impossible : %s}
 {'%s' already has IP addresses} {'%s' a déjà des adresses IP}
 {Searched address: %s} {Adresse recherchée : %s}
 {Search} {Rechercher}
 {Selected by default} {Sélectionnée par défaut}
 {Sensor '%s' not found} {Point de collecte '%s' non trouvé}
 {Sensors} {Sondes}
 {Sessions} {Sessions}
 {Shutdown interface} {Désactiver le port}
 {Shutdown VoIP on this interface} {Désactiver la VoIP sur ce port}
 {%s inactive hosts} {%s machines inactives}
 {... since %s} {... depuis %s}
 {'%s' is a mail host for mail domains} {'%s' est un hébergeur pour des adresses de messagerie}
 {'%s' is a MX} {'%s' est un MX}
 {'%s' is an alias} {'%s' est un alias}
 {'%1$s' is an alias in view '%2$s'} {'%1$s' est un alias dans la vue '%2$s'}
 {%s is a Netmagis group} {%s est un groupe Netmagis}
 {Size of block} {Taille du bloc}
 {%s MAC-Port-VLAN associations found} {%s associations adresse MAC-Port-VLAN trouvées}
 {SMTP authorization management} {Gestion des émetteurs SMTP}
 {SMTP emit right}	{Droit d'émission SMTP}
 {Some accounts match criteria. Choose one} {Plusieurs comptes répondent aux critères. Choisissez celui qui convient}
 {Some accounts match '%s'. Choose one, or ask for a new account} {Plusieurs comptes présentent des similitudes avec '%s'. Choisissez celui qui convient, ou alors demandez la création d'un nouveau compte}
 {Sorry, but you do not have access to any view} {Désolé, mais vous n'avez accès à aucune vue}
 {Sorry, but you do not have any active domain} {Désolé, mais vous n'avez aucun domaine actif}
 {Sort class} {Classe de tri}
 {Special character '%s' is not allowed} {Le caractère spécial '%s' n'est pas autorisé}
 {%s selected network(s).} {%s réseau(x) sélectionné(s).}
 {SSID %s } {SSID %s }
 {'%s' specified more than once} {'%s' spécifié plus d'une fois}
 {Start} {Début}
 {Statistics about MAC/IP addresses} {Statistiques sur les adresses MAC/IP}
 {Statistics by organization} {Stats par établissement}
 {Statistics by user} {Stats par correspondant}
 {Status} {Statut}
 {store} {enregistrement}
 {String '%s' not found} {Chaîne '%s' non trouvée}
 {Submit} {Enregistrer}
 {Sum assoc} {Cumul assoc}
 {Sum auth} {Cumul auth}
 {sums} {cumuls}
 {The '/' character is not valid in the address '%s'} {Le caractère '/' est interdit dans l'adresse '%s'}
 {This host holds mail addresses} {Cette machine héberge des adresses de messagerie}
 {This host is the target of one or more MX} {Cette machine est la cible d'un ou plusieurs MX}
 {This host is the mail relay of one or more domains} {Cette machine est le relais de messagerie d'un ou plusieurs domaines}
 {Title}	{Intitulé}
 {Topod messages} {Messages de topod}
 {Topod status} {Topod status}
 {Topology} {Topo}
 {Topo module} {Module Topo}
 {Total} {Total}
 {to} {vers}
 {Traffic on interface %2$s of %3$s} {Trafic sur l'interface %2$s de %3$s}
 {Traffic on interfaces %s} {Trafic sur les interfaces %s}
 {Traffic on vlan %1$s of interface %2$s of %3$s} {Trafic sur le vlan %1$s de l'interface %2$s de %3$s}
 {Traffic} {Trafic}
 {TTL management} {Gestion du TTL}
 {TTL} {TTL}
 {TTL}		{TTL}
 {Type '%s' not supported} {Type '%s' non supporté}
 {Type the name of group to create} {Entrez le nom du groupe à créer}
 {Type}		{Type}
 {Type}		{Type}
 {Unable to change password of '%1$s': %2$s} {Impossible de changer le mot de passe de '%1$s' : %2$s}
 {Unable to get realm list} {Impossible de récupérer la liste des royaumes}
 {Unable to insert '%1$s' membership: %2$s} {Impossible d'ajouter l'appartenance de '%1$s' aux royaumes : %2$s}
 {Unable to insert account '%1$s': %2$s} {Ajout du compte '%1$s' impossible : %2$s}
 {Unable to insert realm '%1$s': %2$s} {Ajout du royaume '%1$s' impossible: %2$s}
 {Unable to modify '%1$s': %2$s} {Impossible de modifier '%1$s' : %2$s}
 {Unable to remove realm '%1$s': %2$s} {Suppression du royaume '%1$s' impossible: %2$s}
 {Unknown configuration key '%s'} {Clef de configuration '%s' inconnue}
 {Unknown equipemnt (address %s)} {Équipement inconnu (adresse %s)}
 {Unknown module '%s'} {Module '%s' inconnu}
 {Unrecognized authentication method '%s'} {Méthode d'authentication '%s' non reconnue}
 {Up} {Actif}
 {Up/Down} {Actif/Inactif}
 {User '%s' is not in the authentication base} {L'utilisateur '%s' n'est pas dans la base d'authentification}
 {User '%s' is not in the Netmagis base} {L'utilisateur '%s' n'est pas dans la base de Netmagis}
 {User '%s' not authorized} {Utilisateur '%s' non autorisé}
 {User}	{Utilisateur}
 {Use SMTP} {Émettre en SMTP}
 {View management} {Gestion des vues}
 {View}		{Vue}
 {Vlan %1$s: %2$s} {Vlan %1$s : %2$s}
 {vlan=%1$s, voip=%2$s, desc=%3$s} {vlan=%1$s, voip=%2$s, desc=%3$s}
 {Vlan-Id}	{Vlan-id}
 {Vlan id '%s' out of range (1..4094)} {Vlan id '%s' invalide (1..4094)}
 {Vlan management} {Gestion des Vlans}
 {Vlan '%s' is a voice Vlan} {Le vlan '%s' est un Vlan VoIP}
 {Vlan '%s' is not a voice Vlan} {Le vlan '%s' n'est pas un Vlan VoIP}
 {Vlan %s} {le vlan %s}
 {Vlan '%s' not found} {Vlan '%s' non trouvé}
 {vlan=%s} {vlan=%s}
 {Vlans} {Vlans}
 {Vlan} {Vlan}
 {voip=%s} {voip=%s}
 {VoIP Vlan}	{Vlan VoIP}
 {VoIP} {VoIP}
 {Waiting changes} {Changements en attente}
 {Web role edition} {Édition des rôles de Web}
 {Web role management} {Édition des rôles Web}
 {Welcome} {Accueil}
 {Where am I?} {Où suis-je ?}
 {Write} {Modification}
 {yes}		{oui}
 {Yes}		{Oui}
 {You can also <a href="%s">edit more than one interfaces</a> simultaneously} {Vous pouvez également <a href="%s">modifier plusieurs interfaces</a> simultanément}
 {You can not choose both a CIDR and a network} {Vous ne pouvez pas choisir un CIDR et une plage}
 {You cannot read this network} {Vous n'avez pas accès à ce réseau en consultation}
 {You cannot set a DHCP profile without a MAC address} {Impossible de configurer un profil DHCP sans adresse MAC}
 {You can't modify interface %1$s on %2$s} {Vous ne pouvez pas modifier l'interface %1$s sur %2$s}
 {You did not selected any interface} {Vous n'avez pas sélectionné d'interface}
 {You did not specify any criterion} {Vous n'avez saisi aucun critère}
 {You do not have ACL access to this network} {Vous n'avez pas accès à ce réseau pour définir des ACL}
 {You do not have DHCP access to this network} {Vous n'avez pas accès à ce réseau pour DHCP}
 {You don't have access to any DHCP enabled network} {Vous n'avez accès à aucun réseau avec le droit DHCP}
 {You don't have access to DHCP range id '%s'} {Vous n'avez pas accès à l'intervalle DHCP d'id '%s'}
 {You don't have access to these views: %s} {Vous n'avez pas accès à ces vues : %s}
 {You don't have rights on domain '%s'} {Vous n'avez pas les droits sur le domaine '%s'}
 {You don't have rights on host holding mail for '%s'} {Vous n'avez pas les droits sur l'hébergeur de '%s'}
 {You don't have rights on some IP addresses of '%1$s' referenced by alias '%2$s'} {Vous n'avez pas les droits sur certaines adresses IP de '%1$s' référencé par l'alias '%2$s'}
 {You don't have rights on some IP addresses of '%1$s' referenced by MX '%2$s'} {Vous n'avez pas les droits sur certaines adresses IP de '%1$s' référencé par le MX '%2$s'}
 {You don't have rights on some IP addresses of '%s'} {Vous n'avez pas les droits sur certaines adresses IP de '%s'}
 {You don't have rights on '%s'} {Vous n'avez pas les droits sur '%s'}
 {You don't have rights to some relays of domain '%1$s': %2$s} {Vous n'avez pas les droits sur certains relais du domaine '%1$s' : %2$s}
 {You don't have write access to interface '%1$s' on '%2$s'} {Vous n'avez mpas de le droit de modifier l'interface '%1$s' sur '%2$s'}
 {You must choose a CIDR or at least one network} {Vous devez choisir un CIDR ou au moins une plage}
 {You must type a name for the group} {Il faut saisir un nom pour ce groupe}
 {Zone '%s' not found} {Zone '%s' non trouvée}
 {Zone management} {Gestion des zones}


 cfg:general {Paramètres généraux}

 cfg:datefmt:desc {Format d'affichage des dates/heures}
 cfg:datefmt:help {Format d'affichage des dates et des heures, utilisé dans l'édition et l'affichage des données. Voir la page de manuel clock(n) de Tcl.}
 cfg:dayfmt:desc {Format d'affichage des jours}
 cfg:dayfmt:help {Format d'affichage des dates (sans l'heure). Voir la page de manuel clock(n) de Tcl.}
 cfg:authmethod:desc {Méthode d'authentification}
 cfg:authmethod:help {La méthode d'authentification est basée sur un annuaire où trouver les informations sur les personnes (nom, adresse, etc.).}
 cfg:authexpire:desc {Délai maximum d'inactivité}
 cfg:authexpire:help {Durée maximale (en secondes) au bout de laquelle la session authentifiée est conservée. Conservez une valeur élevée (de quelques heures à quelques jours) de façon à ne pas interrompre les actions des utilisateurs.}
 cfg:authcleanup:desc {Délai de suppression des tokens}
 cfg:authcleanup:help {Délai au bout duquel les vieux tokens sont supprimés de la table des sessions (en jours)}
 cfg:authtoklen:desc {Longueur du token}
 cfg:authtoklen:help {Longueur du token d'authentification, en octets. Ne changez cette valeur que si vous comprenez de quoi il s'agit.}
 cfg:pageformat:desc {Format de papier}
 cfg:pageformat:help {Format de papier pour les pages imprimables.}
 cfg:schemaversion:desc {Version de schéma}
 cfg:schemaversion:help {Version actuelle du schéma de la base de données, utilisée pour des tests de cohérence. Ce paramètre n'est pas modifiable.}

 cfg:dns {Paramètres DNS}

 cfg:defuser:desc {Utilisateur par défaut}
 cfg:defuser:help {L'utilisateur par défaut est utilisé dans les programmes Netmagis en ligne de commande lorsque le login de l'utilisateur n'existe pas dans la base Netmagis.}

 cfg:dhcp {Paramètres DHCP}

 cfg:dhcpdefdomain:desc {Domaine par défaut}
 cfg:dhcpdefdomain:help {Domaine envoyé par défaut aux clients DHCP sans profil.}
 cfg:dhcpdefdnslist:desc {Serveurs DNS par défaut}
 cfg:dhcpdefdnslist:help {Serveurs DNS envoyés par défaut aux clients DHCP sans profil, séparés par des espaces.}
 cfg:default_lease_time:desc {default_lease_time}
 cfg:default_lease_time:help {Valeur du parameter DHCP "default_lease_time" utilisé lors de la génération d'intervalles dynamiques, en secondes. Cette valeur est utilisée si le parameter spécifique de l'intervalle est nul.}
 cfg:max_lease_time:desc {max_lease_time}
 cfg:max_lease_time:help {Valeur du parameter DHCP "max_lease_time" utilisé lors de la génération d'intervalles dynamiques, en secondes.  Cette valeur est utilisée si le parameter spécifique de l'intervalle est nul.}
 cfg:min_lease_time:desc {min_lease_time}
 cfg:min_lease_time:help {Valeur minimale des parameters DHCP spécifiés dans les intervalles dynamiques. Cette valeur permet uniquement d'éviter qu'un correspondant réseau précise des parameters de bail trop petits et génère un trafic important.}

 cfg:topo {Paramètres du module "Topo"}

 cfg:topoactive:desc {Activation de Topo}
 cfg:topoactive:help {Cocher cette case pour activer l'accès à la fonctionnalité "Topo".}
 cfg:defdomain:desc {Domaine par défaut}
 cfg:defdomain:help {Domaine par défaut, car certains équipements ne se signalement pas avec un nom pleinement qualifié.}
 cfg:topofrom:desc {"From" des mails de topo}
 cfg:topofrom:help {Champ "From" des mails envoyés par le démon topod lors des détections de modification ou d'anomalie.}
 cfg:topoto:desc {Destinataire des mails de topo}
 cfg:topoto:help {Champ "To" des mails envoyés par le démon topod lors des détection de modification ou d'anomalie.}
 cfg:topographddelay:desc {Délai de topographd}
 cfg:topographddelay:help {Délai d'attente (en secondes) entre deux itérations de la boucle principale du démon topographd. Exemple: 5}
 cfg:toposendddelay:desc {Délai de toposendd}
 cfg:toposendddelay:help {Délai d'attente (en secondes) entre deux itérations de la boucle principale du démon toposendd. Exemple: 5}
 cfg:topomaxstatus:desc {Max statut}
 cfg:topomaxstatus:help {Nombre maximum de lignes de statut conservées dans la base de données. Exemple: 100}
 cfg:sensorexpire:desc {Délai d'expiration des sondes}
 cfg:sensorexpire:help {Délai (en jours) avant qu'une sonde expire et soit supprimée de la base. Exemple: 30}
 cfg:modeqexpire:desc {Délai d'expiration des modifications d'équiments}
 cfg:modeqexpire:help {Délai (en jours) avant qu'une entrée "équipement modifié" soit expirée de la base de donnés. Exemple: 30}
 cfg:ifchangeexpire:desc {Délai d'expiration des changements d'interfaces}
 cfg:ifchangeexpire:help {Délai (en jours) avant qu'une entrée "changement d'interface en attente" soit expirée de la base de donnés. Exemple: 30}
 cfg:fullrancidmin:desc {Heure minimum de fullrancid}
 cfg:fullrancidmin:help {Heure minimum (0..24) de démarrage de l'opération quotidienne de "full-rancid". Exemple: 2}
 cfg:fullrancidmax:desc {Heure maximum de fullrancid}
 cfg:fullrancidmax:help {Heure maximum (0..24) de démarrage de l'opération quotidienne de "full-rancid". Exemple: 4}

 cfg:mac {Paramètres du module "MAC"}

 cfg:macactive:desc {Activation de Mac}
 cfg:macactive:help {Cocher cette case pour activer l'accès à la fonctionnalité "Mac".}

 cfg:authldap {Paramètres pour l'authentification LDAP}

 cfg:ldapurl:desc {Serveur LDAP}
 cfg:ldapurl:help {URL d'accès au serveur LDAP. Exemple : ldaps://ldap.domaine.fr:636/}
 cfg:ldapbinddn:desc {Bind DN}
 cfg:ldapbinddn:help {DN permettant l'authentification sur le serveur LDAP. Exemple : cn=admin,dc=domaine,dc=fr}
 cfg:ldapbindpw:desc {Mot de passe de Bind}
 cfg:ldapbindpw:help {Mot de passe pour le DN permettant l'authentification sur le serveur LDAP.}
 cfg:ldapbasedn:desc {DN de base}
 cfg:ldapbasedn:help {DN de base à partir duquel il faut faire les requêtes sur les personnes. Exemple : ou=people,dc=domaine,dc=fr}
 cfg:ldapsearchlogin:desc {Requête de recherche d'utilisateur}
 cfg:ldapsearchlogin:help {Requête LDAP pour chercher un utilisateur à partir de son login. Exemple : "(&(objectClass=inetOrgPerson)(uid=%s))"}
 cfg:ldapattrlogin:desc {Attribut "login"}
 cfg:ldapattrlogin:help {Attribut LDAP correspondant au login. Exemple : "uid"}
 cfg:ldapattrname:desc {Attribut "nom"}
 cfg:ldapattrname:help {Attribut LDAP correspondant au nom. Exemple : "sn"}
 cfg:ldapattrgivenname:desc {Attribut "prénom"}
 cfg:ldapattrgivenname:help {Attribut LDAP correspondant au prénom. Exemple : "givenName". Les attributs peuvent être vides ou composés d'un ou plusieurs attributs LDAP qui seront accolés à l'affichage.}
 cfg:ldapattrmail:desc {Attribut "mél"}
 cfg:ldapattrmail:help {Attribut LDAP correspondant à l'adresse mail de la personne. Exemple : "mail". Les attributs peuvent également être vides ou composés d'un ou plusieurs attributs LDAP qui seront accolés à l'affichage.}
 cfg:ldapattrphone:desc {Attribut "téléphone"}
 cfg:ldapattrphone:help {Attribut LDAP correspondant au numéro de téléphone. Exemple : "telephoneNumber". Les attributs peuvent être vides, ou composés d'un ou plusieurs attributs LDAP qui seront accolés à l'affichage.}
 cfg:ldapattrmobile:desc {Attribut "portable"}
 cfg:ldapattrmobile:help {Attribut LDAP correspondant au numéro de téléphone mobile. Exemple : "". Les attributs peuvent être vides ou composés d'un ou plusieurs attributs LDAP qui seront accolés à l'affichage.}
 cfg:ldapattrfax:desc {Attribut "fax"}
 cfg:ldapattrfax:help {Attribut LDAP correspondant au numéro de fax. Exemple : "facsimileTelephoneNumber". Les attributs peuvent être vides ou composés d'un ou plusieurs attributs LDAP qui seront accolés à l'affichage.}
 cfg:ldapattraddr:desc {Attribut "adresse"}
 cfg:ldapattraddr:help {Attribut LDAP correspondant à l'adresse. Exemple : "postalAddress postalCode l". Les attributs peuvent être vides ou composés d'un ou plusieurs attributs LDAP qui seront accolés à l'affichage.}

 cfg:authpgsql {Paramètres pour l'authentification interne}

 cfg:authpgminpwlen:desc {Longueur minimum des mots de passe}
 cfg:authpgminpwlen:help {Longueur minimum autorisée pour les mots de passe saisis dans le module d'authentification interne.}
 cfg:authpgmaxpwlen:desc {Longueur maximum des mots de passe}
 cfg:authpgmaxpwlen:help {Longueur maximum autorisée pour les mots de passe saisis dans le module d'authentification interne.}
 cfg:authpgmailfrom:desc {"From" des mails de modification de passwd}
 cfg:authpgmailfrom:help {Champ "From" des mails envoyés par l'application à un utilisateur lors des changements de mot de passe.}
 cfg:authpgmailreplyto:desc {"Reply-To" des mails de modification de passwd}
 cfg:authpgmailreplyto:help {Champ "Reply-To" des mails envoyés par l'application à un utilisateur lors des changements de mot de passe.}
 cfg:authpgmailcc:desc {"Cc" des mails de modification de passwd}
 cfg:authpgmailcc:help {Destinataire(s) auxiliaires des mail envoyés par l'application à un utilisateur lors des changements de mot de passe.  Cela peut éventuellement être une liste d'adresses, l'espace faisant office de séparateur.}
 cfg:authpgmailbcc:desc {"Bcc" des mails de modification de passwd}
 cfg:authpgmailbcc:help {Destinataire(s) caché(s) des mail envoyés par l'application à un utilisateur lors des changements de mot de passe.  Cela peut éventuellement être une liste d'adresses, l'espace faisant office de séparateur.}
 cfg:authpgmailsubject:desc {"Subject" des mails de moditication de passwd}
 cfg:authpgmailsubject:help {Champ "Subject" des mails envoyés par l'application à un utilisateur lors des changements de mot de passe.}
 cfg:authpgmailbody:desc {Corps du mail de modification de passwd}
 cfg:authpgmailbody:help {Corps des mails envoyés par l'application à un utilisateur lors des changements de mot de passe. Les parameters suivants sont substitués: <ul><li>%1$s : login de l'utilisateur</li> <li>%2$s : mot de passe généré</li></ul>}
 cfg:authpggroupes:desc {Groupes Web autorisés}
 cfg:authpggroupes:help {Liste de groupes (conformément à l'authentification Apache) autorisés pour la création d'un utilisateur.  Si la liste est vide, tous les groupes existants dans la base d'authentification sont autorisés.}
}
