#
# Netmagis server translation messages
#

::msgcat::mcmset fr {
 {Not found} {Ressource non trouvée}
 {Forbidden} {Ressource non autorisée}
 {Forbidden (%s)} {Ressource non autorisée (%s)}
 {View '%s' not found} {Vue '%s' non trouvée}
 {Table '%s' not found} {Table '%s' non trouvée}
 {Network '%s' not found} {Réseau '%s' non trouvé}
 {Domain '%s' not found} {Domaine '%s' non trouvé}
 {Domain-id '%s' not found} {Identificateur de domaine '%s' non trouvé}
 {'test' needs view/name/domain parameters} {'test' nécessite les paramètres view/name/domain}
 {No view selected} {Aucune vue sélectionnée}
 {You don't have access to these views: %s} {Vous n'avez pas accès à ces vues: %s}
 {You don't have rights on domain '%s'} {Vous n'avez pas accès au domaine '%s'}
 {Internal error: invalid context '%s'} {Erreur interne: contexte '%s' invalide}
 {%1$s is an alias of host %2$s in view %3$s} {%1$s est un alias sur %2$s dans la vue %3$s}
 {You don't have rights on some IP addresses of '%1$s'} {Vous n'avez pas les droits sur des adresses IP de '%1$s'}
 {You don't have rights on some IP addresses of '%1$s' referenced by alias '%2$s'} {Vous n'avez pas les droits sur des adresses IP de '%1$s' référencé par l'alias '%2$s'}
 {You don't have rights on some IP addresses of '%1$s' referenced by MX '%2$s'} {Vous n'avez pas les droits sur des adresses IP de '%1$s' référencé par le MX '%2$s'}
 {Internal error: invalid parameter '%1$s' for '%2$s'} {Erreur interne : paramètre '%1$s' invalide pour '%2$s'}
 {'%s' is a MX} {'%s' est un MX}
 {Internal error: id '%s' doesn't exists for a mail host} {Erreur interne : l'id '%s' n'existe pas pour le mail host}
 {%1$s in view %2$s is a mail address hosted by %3$s in view %4$s} {%1$s dans la vue %2$s est une adresse mail hébergée par %3$s dans la vue %4$s}
 {You don't have rights on host holding mail for '%s'} {Vous n'avez pas les droits sur l'hébergeur de l'adresse mail '%s'}
 {'%1$s' is not a mail role in view '%2$s'} {'%1$s' n'est pas un rôle de messagerie dans la vue '%2$s'}
 {'%s' is a mail host for mail domains} {'%s' est un hébergeur de messagerie}
 {'%1$s' has IP addresses in view '%2$s'} {'%1$s' a des adresses IP dans la vue '%2$s'}
 {Name '%1$s' is not a host in view '%2$s'} {Le nom '%1$s' n'est pas une machine dans la vue '%2$s'}
}
