#!/bin/sh

#
# Attempt to get a list of all messages displayed in the
# Netmagis source code, and compare this list with the
# French translation.
#
# The list extracted from source code is not exact, since
# English messages in the code can reside in variables and
# cannot be found by the regexp which catch patterns such
# as [mc "string constant"...]
#
# History:
#   2013/03/?? : pda/jean : design
#   2013/06/02 : pda      : documented and added to the repo
#

MSGFILE=common/msgs/fr.msg

TMP1=/tmp/chkmsg.$$.used
TMP2=/tmp/chkmsg.$$.defined

#
# Get all messages used in the Netmagis code
#

grep -hr "\[mc [\"{]" * \
    | sed \
	-e 's/.*\[[m]c "\([^"]*\)".*/\1/' \
	-e 's/.*\[[m]c {\([^}]*\)}.*/\1/' \
    | sort --ignore-case \
    | uniq \
    > $TMP1

#
# Get all messages defined in the message file
#

sed -n \
	-e '/^ *$/d' \
	-e 's/^ {\([^}]*\)}.*/\1/p' \
	-e 's/^ \([^ ][^ ]*\) .*/\1/p' \
	$MSGFILE \
    | sort --ignore-case \
    > $TMP2

echo "< used > defined"
diff $TMP1 $TMP2

#
# Get all messages used in the Netmagis code, but hidden by a variable
#

grep -r '\[mc \$' * | grep -v grep

rm -f $TMP1 $TMP2
