#!/bin/sh

#
# Get a list of all defined functions in libnetmagis.tcl and
# check if they are used in at least one script.
#
# History:
#   2012/12/08 : pda : design
#   2013/06/02 : pda : add this script to the repo
#

LIB=common/libnetmagis.tcl

case `uname` in
    FreeBSD)	EXTRE="-E" ;;
    Linux)	EXTRE="-r" ;;
    *)		echo "System `uname` not supported" >&2 ; exit 1 ;;
esac

TMP=/tmp/chkproc.$$

# $1 = file
get_proc ()
{
    sed $EXTRE -n "s/^[[:space:]]*(proc|method)[[:space:]]*([^[:space:]]+).*/\2/p" $1
}

not_used ()
{
    tee $TMP
    if [ `wc -l < $TMP` = 0 ]
    then
	echo "(not used) <--------"
    fi
}

for f in `get_proc $LIB`
do
    echo "$f"
    egrep -r "^[^#]*[\[[:space:]]$f([[:space:]]|.*)$" * |
	sed $EXTRE \
	    -e "/:[[:space:]]*(proc|method)/d" \
	    -e "s/:.*//" \
	    |
	sort -u |
	not_used |
	sed "s/^/	/"
done

exit 0
