#!/bin/sh

#
# $Id$
#
# Ce script est un faux "sendmail" utilisé pour collecter les mails
# envoyés par le vrai "rancid" et les rediriger vers la sortie 3
# afin d'éviter le mélange avec d'autres informations de log qui
# ne nous intéressent pas.
#
# Historique
#   2007/07/03 : pda/jean : conception
#   2010/10/20 : pda/jean : intégration dans topo
#

(
	sed '1,/^$/ {
			s/^To:.*//
			s/^Precedence:.*//
			s/^Subject: />>> /
		}'
) >&3
