#!/bin/sh -x

exit


PGPASSWORD=mot-de-passe-de-mac
export PGPASSWORD 

dropdb mac
./creer-base
./charge-eq
./charge-vlan


PGDATABASE=mac
export PGDATABASE

./oui/dropoui
./oui.createoui
./oui/updateoui -r

